### ISSUE TITLE
Margin in LMCL loss might have some problems.

### ISSUE THREAD

**Issue by ZhangXLaurence** [YirongMao/softmax_variants#1]
Hi,
According to LMCL paper, the margin was only computed between feature x and its own class weight W. 
Hence I think label should be passed into your implementation and LMCL_loss should be modified.

**Comment by YirongMao** [comment]
Hello, 
The code for LMCL paper is implemented by myself, not by the original authors. 
I didn't test my code on face datasets.
If you test it and find any problem, be free to contact me.
